apiVersion: v1
data:
  auth.json: eyJjbGllbnRfaWQiOiI1NmMxYmQxNC0zYmE3LTQ4MDQtYjQ3Yi1kNDZkZTZkY2UzM2UiLCJjbGllbnRfc2VjcmV0IjoialVUOFF+QXIuYWRLZXVxRDBxdDNPckFJTTg1azdJOVlqZDB0NGNSdCIsImlzc3Vlcl91cmwiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wNmE4YTA4Ni1hZTZlLTQ1YjUtYTIyZS1hZDkwZGUyMzAxM2UvdjIuMCJ9
  clientAuthenticationParameters: eyJwcml2YXRlS2V5IjoiZmlsZTovLy9tbnQvc2VjcmV0L2F1dGguanNvbiIsImlzc3VlclVybCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzA2YThhMDg2LWFlNmUtNDViNS1hMjJlLWFkOTBkZTIzMDEzZS92Mi4wIiwiYXVkaWVuY2UiOiJhcGk6Ly81NmMxYmQxNC0zYmE3LTQ4MDQtYjQ3Yi1kNDZkZTZkY2UzM2UvLmRlZmF1bHQiLCJzY29wZSI6ImFwaTovLzU2YzFiZDE0LTNiYTctNDgwNC1iNDdiLWQ0NmRlNmRjZTMzZS8uZGVmYXVsdCJ9
  clientAuthenticationPlugin: b3JnLmFwYWNoZS5wdWxzYXIuY2xpZW50LmltcGwuYXV0aC5vYXV0aDIuQXV0aGVudGljYXRpb25PQXV0aDI=
kind: Secret
metadata:
  name: 56c1bd14-3ba7-4804-b47b-d46de6dce33e
type: Opaque