#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

## deployed withh emptyDir
volumes:
  persistence: false

# disabled AntiAffinity
affinity:
  anti_affinity: false

# disable auto recovery
components:
  autorecovery: false
  pulsar_manager: false

## disable monitoring stack
monitoring:
  # monitoring - prometheus
  prometheus: false
  # monitoring - grafana
  grafana: false
  # monitoring - node_exporter
  node_exporter: false

images:
  zookeeper:
    repository: mesh-worker-service-integration-pulsar
    tag: latest
  bookie:
    repository: mesh-worker-service-integration-pulsar
    tag: latest
  autorecovery:
    repository: mesh-worker-service-integration-pulsar
    tag: latest
  broker:
    repository: mesh-worker-service-integration-pulsar
    tag: latest
  functions:
    repository: mesh-worker-service-integration-pulsar
    tag: latest
  proxy:
    repository: mesh-worker-service-integration-pulsar
    tag: latest

zookeeper:
  replicaCount: 1

bookkeeper:
  replicaCount: 1
  metadata:
    image:
      repository: mesh-worker-service-integration-pulsar
      tag: latest
  configData:
    # `BOOKIE_MEM` is used for `bookie shell`
    BOOKIE_MEM: >
      -Xms128m
      -Xmx256m
      -XX:MaxDirectMemorySize=256m
    # we use `bin/pulsar` for starting bookie daemons
    PULSAR_MEM: >
      -Xms128m
      -Xmx256m
      -XX:MaxDirectMemorySize=256m
    PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+AggressiveOpts
      -XX:+DoEscapeAnalysis
      -XX:ParallelGCThreads=4
      -XX:ConcGCThreads=4
      -XX:G1NewSizePercent=50
      -XX:+DisableExplicitGC
      -XX:-ResizePLAB
      -XX:+ExitOnOutOfMemoryError
      -XX:+PerfDisableSharedMem
    PULSAR_PREFIX_journalMaxSizeMB: "200"

pulsar_metadata:
  image:
    repository: mesh-worker-service-integration-pulsar
    tag: latest

functions:
  configData:
    functionsWorkerServiceNarPackage: /pulsar/mesh-worker-service.nar
    functionsWorkerServiceCustomConfigs:
      uploadEnabled: true
      functionEnabled: true
      sinkEnabled: true
      sourceEnabled: true
      functionRunnerImages:
        "JAVA": streamnative/pulsar-functions-java-runner:2.10.0.0-rc10
        "PYTHON": streamnative/pulsar-functions-python-runner:2.10.0.0-rc10
        "GO": streamnative/pulsar-functions-go-runner:2.10.0.0-rc10

broker:
  replicaCount: 1
  configData:
    ## Enable `autoSkipNonRecoverableData` since bookkeeper is running
    ## without persistence
    autoSkipNonRecoverableData: "true"
    # storage settings
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"
    enablePackagesManagement: "true"
    PULSAR_PREFIX_enablePackagesManagement: "true"

proxy:
  replicaCount: 1

auth:
  authorization:
    enabled: false
  authentication:
    enabled: true
    provider: "oauth2"
    oauth2:
      issuerUrl: https://sts.windows.net/06a8a086-ae6e-45b5-a22e-ad90de23013e/
      issuerUrlParam: https://sts.windows.net/06a8a086-ae6e-45b5-a22e-ad90de23013e/v2.0
      audience: api://56c1bd14-3ba7-4804-b47b-d46de6dce33e
      audienceParam: api://56c1bd14-3ba7-4804-b47b-d46de6dce33e/.default
      brokerClientCredential: '{"client_id":"56c1bd14-3ba7-4804-b47b-d46de6dce33e","client_secret":"pBz8Q~ILXDKvC6-NS~zSlYsMF31avrrJsWo6PbNY"}'
      subjectClaim: appid
      adminScope: appid
      adminScopeParam: api://56c1bd14-3ba7-4804-b47b-d46de6dce33e/.default
      authenticationProviders: io.streamnative.pulsar.broker.authentication.AuthenticationProviderOAuth