name: Precommit - Unit Tests
on: [pull_request]
permissions: read-all
jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: clean disk
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
          df -h

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.0/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --help

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto generate crd model
        run: ./scripts/generate-crd.sh

      - name: Format license
        run: mvn license:format

      - name: Run mesh worker service unit test
        run: mvn clean install

      - name: Save PR sha
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
          echo ${{ github.event.pull_request.head.repo.full_name }} > ./pr/repo
          echo ${{ github.event.pull_request.head.sha }} > ./pr/sha

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
